### 1. Створення студента
POST http://localhost:9090/university/students
Content-Type: application/json

{
  "firstName": "Ivan",
  "lastName": "Petrov",
  "email": "ivan@example.com",
  "age": 20
}

### 2. Отримання всіх студентів
GET http://localhost:9090/university/students

### 3. Отримання студента за ID
GET http://localhost:9090/university/students/1

### 4. Оновлення студента
PUT http://localhost:9090/university/students/1
Content-Type: application/json

{
  "firstName": "Ivan",
  "lastName": "Sydorov",
  "email": "ivan.s@example.com",
  "age": 21
}

### 5. Видалення студента
DELETE http://localhost:9090/university/students/1